---
- name: Use syslog for php-fpm
  lineinfile: state="present" dest="{{ php_conf_path }}/php-fpm.conf" regexp=";?error_log = .+$" line="error_log = syslog"
  when: syslog_name != ""

- name: Set emergency restart threshold for php-fpm
  lineinfile: state="present" dest="{{ php_conf_path }}/php-fpm.conf" regexp=";?emergency_restart_threshold = .+$" line="emergency_restart_threshold = {{fpm_emergency_restart_threshold}}"

- name: Set emergency restart interval for php-fpm
  lineinfile: state="present" dest="{{ php_conf_path }}/php-fpm.conf" regexp=";?emergency_restart_interval = .+$" line="emergency_restart_interval = {{fpm_emergency_restart_interval}}"

- name: Set process control timeout for php-fpm
  lineinfile: state="present" dest="{{ php_conf_path }}/php-fpm.conf" regexp=";?process_control_timeout = .+$" line="process_control_timeout = {{fpm_process_control_timeout}}"

- name: Use custom pool conf (PHP 7.0)
  template: src="php7.0-www.conf.j2" dest="{{ php_conf_path }}/pool.d/www.conf"
  when: "'php7.0-fpm' in php_packages"

- name: Use custom pool conf (PHP 5)
  template: src="php5-www.conf.j2" dest="{{ php_conf_path }}/pool.d/www.conf"
  when: "'php5.6-fpm' in php_packages"
